
name: k8spring ci

on:
  pull_request:
    branches: [ main ]

jobs:

  # spring test
  spring-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Spring tests
        run: mvn clean verify
        working-directory: back/spring

  # react test
  react-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: front/react
        run: npm ci

      - name: Run lint
        working-directory: front/react
        run: npm run lint

      - name: Run tests
        working-directory: front/react
        run: npm test

  # build
  build:
    runs-on: ubuntu-latest
    needs: [ spring-tests, react-tests ]

    steps:
      - uses: actions/checkout@v4

      # setup java version
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # TEMP debug java version
      - name: Verify Java
        run: |
          java -version
          mvn -version

      # spring build
      - name: Build backend (Spring)
        run: mvn clean package -DskipTests
        working-directory: back/spring

      # react build
      - name: Build frontend (React)
        run: |
          npm ci
          npm run build
        working-directory: front/react

#  # docker images build
#  docker-build:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Build Docker images
#        run: docker compose build

